import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PrototypeNav } from "@/components/PrototypeNav"
import "./globals.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen bg-black text-white selection:bg-purple-500/30`}>
        <PrototypeNav />
        {children}
        <div id="amplify-ready" className="hidden" />
      </body>
    </html>
  )
}
